version: '3.6'

services:

  simple-file-server:
    build: .
    image: oU2DADnianJ8/simple-temp-file-server
    ports:
      - "4000:4000"
    environment:
      - LOG_LEVEL=debug
      - LOCATION_BASE_URL=http://localhost:4000
      # - WRITE_SHARED_KEY=abc
      # - READ_SHARED_KEY=123

